version: '3.6'
services:
  node:
    image: node:18
    container_name: ddev-${DDEV_SITENAME}-node
    working_dir: /var/www/html/frontend
    volumes:
      - ../frontend:/var/www/html/frontend
    ports:
      - "3000:3000"
    command: >
      bash -c "npm install && npm start"