version: '3.6'

services:
  node:
    image: node:20
    container_name: ddev-${DDEV_SITENAME}-node
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
